MERGE dim.DIM_EQUIPE AS target
USING
(
    SELECT
        ? AS equipe_original_id,
        ? AS nome_equipe,
        ? AS codigo_equipe,
        ? AS tipo_equipe,
        ? AS categoria_equipe,
        ? AS regional,
        ? AS estado_sede,
        ? AS cidade_sede,
        ? AS lider_equipe_id,
        ? AS nome_lider,
        ? AS email_lider,
        ? AS meta_mensal_equipe,
        ? AS meta_trimestral_equipe,
        ? AS meta_anual_equipe,
        ? AS qtd_meta_vendas_mes,
        ? AS qtd_membros_atual,
        ? AS qtd_membros_ideal,
        ? AS total_vendas_mes_anterior,
        ? AS percentual_meta_mes_anterior,
        ? AS ranking_ultimo_mes,
        ? AS data_criacao,
        ? AS data_ultima_atualizacao,
        ? AS data_inativacao,
        ? AS situacao,
        ? AS eh_ativa,
        ? AS observacoes
) AS source
    ON target.equipe_original_id = source.equipe_original_id
WHEN MATCHED THEN
    UPDATE SET
        target.nome_equipe = source.nome_equipe,
        target.codigo_equipe = source.codigo_equipe,
        target.tipo_equipe = source.tipo_equipe,
        target.categoria_equipe = source.categoria_equipe,
        target.regional = source.regional,
        target.estado_sede = source.estado_sede,
        target.cidade_sede = source.cidade_sede,
        target.lider_equipe_id = source.lider_equipe_id,
        target.nome_lider = source.nome_lider,
        target.email_lider = source.email_lider,
        target.meta_mensal_equipe = source.meta_mensal_equipe,
        target.meta_trimestral_equipe = source.meta_trimestral_equipe,
        target.meta_anual_equipe = source.meta_anual_equipe,
        target.qtd_meta_vendas_mes = source.qtd_meta_vendas_mes,
        target.qtd_membros_atual = source.qtd_membros_atual,
        target.qtd_membros_ideal = source.qtd_membros_ideal,
        target.total_vendas_mes_anterior = source.total_vendas_mes_anterior,
        target.percentual_meta_mes_anterior = source.percentual_meta_mes_anterior,
        target.ranking_ultimo_mes = source.ranking_ultimo_mes,
        target.data_criacao = source.data_criacao,
        target.data_ultima_atualizacao = source.data_ultima_atualizacao,
        target.data_inativacao = source.data_inativacao,
        target.situacao = source.situacao,
        target.eh_ativa = source.eh_ativa,
        target.observacoes = source.observacoes
WHEN NOT MATCHED BY TARGET THEN
    INSERT
    (
        equipe_original_id,
        nome_equipe,
        codigo_equipe,
        tipo_equipe,
        categoria_equipe,
        regional,
        estado_sede,
        cidade_sede,
        lider_equipe_id,
        nome_lider,
        email_lider,
        meta_mensal_equipe,
        meta_trimestral_equipe,
        meta_anual_equipe,
        qtd_meta_vendas_mes,
        qtd_membros_atual,
        qtd_membros_ideal,
        total_vendas_mes_anterior,
        percentual_meta_mes_anterior,
        ranking_ultimo_mes,
        data_criacao,
        data_ultima_atualizacao,
        data_inativacao,
        situacao,
        eh_ativa,
        observacoes
    )
    VALUES
    (
        source.equipe_original_id,
        source.nome_equipe,
        source.codigo_equipe,
        source.tipo_equipe,
        source.categoria_equipe,
        source.regional,
        source.estado_sede,
        source.cidade_sede,
        source.lider_equipe_id,
        source.nome_lider,
        source.email_lider,
        source.meta_mensal_equipe,
        source.meta_trimestral_equipe,
        source.meta_anual_equipe,
        source.qtd_meta_vendas_mes,
        source.qtd_membros_atual,
        source.qtd_membros_ideal,
        source.total_vendas_mes_anterior,
        source.percentual_meta_mes_anterior,
        source.ranking_ultimo_mes,
        source.data_criacao,
        source.data_ultima_atualizacao,
        source.data_inativacao,
        source.situacao,
        source.eh_ativa,
        source.observacoes
    );
