MERGE dim.DIM_DESCONTO AS target
USING
(
    SELECT
        ? AS desconto_original_id,
        ? AS codigo_desconto,
        ? AS nome_campanha,
        ? AS descricao,
        ? AS tipo_desconto,
        ? AS metodo_desconto,
        ? AS valor_desconto,
        ? AS min_valor_compra_regra,
        ? AS max_valor_desconto_regra,
        ? AS max_usos_por_cliente,
        ? AS max_usos_total,
        ? AS aplica_em,
        ? AS restricao_produtos,
        ? AS restricao_clientes,
        ? AS data_inicio_validade,
        ? AS data_fim_validade,
        ? AS origem_campanha,
        ? AS canal_divulgacao,
        ? AS total_usos_realizados,
        ? AS total_receita_gerada,
        ? AS total_desconto_concedido,
        ? AS situacao,
        ? AS eh_ativo,
        ? AS requer_aprovacao,
        ? AS eh_cumulativo,
        ? AS data_criacao,
        ? AS data_ultima_atualizacao,
        ? AS usuario_criador,
        ? AS observacoes
) AS source
    ON target.desconto_original_id = source.desconto_original_id
WHEN MATCHED THEN
    UPDATE SET
        target.codigo_desconto = source.codigo_desconto,
        target.nome_campanha = source.nome_campanha,
        target.descricao = source.descricao,
        target.tipo_desconto = source.tipo_desconto,
        target.metodo_desconto = source.metodo_desconto,
        target.valor_desconto = source.valor_desconto,
        target.min_valor_compra_regra = source.min_valor_compra_regra,
        target.max_valor_desconto_regra = source.max_valor_desconto_regra,
        target.max_usos_por_cliente = source.max_usos_por_cliente,
        target.max_usos_total = source.max_usos_total,
        target.aplica_em = source.aplica_em,
        target.restricao_produtos = source.restricao_produtos,
        target.restricao_clientes = source.restricao_clientes,
        target.data_inicio_validade = source.data_inicio_validade,
        target.data_fim_validade = source.data_fim_validade,
        target.origem_campanha = source.origem_campanha,
        target.canal_divulgacao = source.canal_divulgacao,
        target.total_usos_realizados = source.total_usos_realizados,
        target.total_receita_gerada = source.total_receita_gerada,
        target.total_desconto_concedido = source.total_desconto_concedido,
        target.situacao = source.situacao,
        target.eh_ativo = source.eh_ativo,
        target.requer_aprovacao = source.requer_aprovacao,
        target.eh_cumulativo = source.eh_cumulativo,
        target.data_criacao = source.data_criacao,
        target.data_ultima_atualizacao = source.data_ultima_atualizacao,
        target.usuario_criador = source.usuario_criador,
        target.observacoes = source.observacoes
WHEN NOT MATCHED BY TARGET THEN
    INSERT
    (
        desconto_original_id,
        codigo_desconto,
        nome_campanha,
        descricao,
        tipo_desconto,
        metodo_desconto,
        valor_desconto,
        min_valor_compra_regra,
        max_valor_desconto_regra,
        max_usos_por_cliente,
        max_usos_total,
        aplica_em,
        restricao_produtos,
        restricao_clientes,
        data_inicio_validade,
        data_fim_validade,
        origem_campanha,
        canal_divulgacao,
        total_usos_realizados,
        total_receita_gerada,
        total_desconto_concedido,
        situacao,
        eh_ativo,
        requer_aprovacao,
        eh_cumulativo,
        data_criacao,
        data_ultima_atualizacao,
        usuario_criador,
        observacoes
    )
    VALUES
    (
        source.desconto_original_id,
        source.codigo_desconto,
        source.nome_campanha,
        source.descricao,
        source.tipo_desconto,
        source.metodo_desconto,
        source.valor_desconto,
        source.min_valor_compra_regra,
        source.max_valor_desconto_regra,
        source.max_usos_por_cliente,
        source.max_usos_total,
        source.aplica_em,
        source.restricao_produtos,
        source.restricao_clientes,
        source.data_inicio_validade,
        source.data_fim_validade,
        source.origem_campanha,
        source.canal_divulgacao,
        source.total_usos_realizados,
        source.total_receita_gerada,
        source.total_desconto_concedido,
        source.situacao,
        source.eh_ativo,
        source.requer_aprovacao,
        source.eh_cumulativo,
        source.data_criacao,
        source.data_ultima_atualizacao,
        source.usuario_criador,
        source.observacoes
    );
