MERGE dim.DIM_CLIENTE AS target
USING
(
    SELECT
        ? AS cliente_original_id,
        ? AS nome_cliente,
        ? AS email,
        ? AS telefone,
        ? AS cpf_cnpj,
        ? AS data_nascimento,
        ? AS genero,
        ? AS tipo_cliente,
        ? AS segmento,
        ? AS score_credito,
        ? AS categoria_valor,
        ? AS endereco_completo,
        ? AS bairro,
        ? AS cidade,
        ? AS estado,
        ? AS pais,
        ? AS cep,
        ? AS data_primeiro_cadastro,
        ? AS data_ultima_compra,
        ? AS data_ultima_atualizacao,
        ? AS eh_ativo,
        ? AS aceita_email_marketing,
        ? AS eh_cliente_vip
) AS source
    ON target.cliente_original_id = source.cliente_original_id
WHEN MATCHED THEN
    UPDATE SET
        target.nome_cliente = source.nome_cliente,
        target.email = source.email,
        target.telefone = source.telefone,
        target.cpf_cnpj = source.cpf_cnpj,
        target.data_nascimento = source.data_nascimento,
        target.genero = source.genero,
        target.tipo_cliente = source.tipo_cliente,
        target.segmento = source.segmento,
        target.score_credito = source.score_credito,
        target.categoria_valor = source.categoria_valor,
        target.endereco_completo = source.endereco_completo,
        target.bairro = source.bairro,
        target.cidade = source.cidade,
        target.estado = source.estado,
        target.pais = source.pais,
        target.cep = source.cep,
        target.data_primeiro_cadastro = source.data_primeiro_cadastro,
        target.data_ultima_compra = source.data_ultima_compra,
        target.data_ultima_atualizacao = source.data_ultima_atualizacao,
        target.eh_ativo = source.eh_ativo,
        target.aceita_email_marketing = source.aceita_email_marketing,
        target.eh_cliente_vip = source.eh_cliente_vip
WHEN NOT MATCHED BY TARGET THEN
    INSERT
    (
        cliente_original_id,
        nome_cliente,
        email,
        telefone,
        cpf_cnpj,
        data_nascimento,
        genero,
        tipo_cliente,
        segmento,
        score_credito,
        categoria_valor,
        endereco_completo,
        bairro,
        cidade,
        estado,
        pais,
        cep,
        data_primeiro_cadastro,
        data_ultima_compra,
        data_ultima_atualizacao,
        eh_ativo,
        aceita_email_marketing,
        eh_cliente_vip
    )
    VALUES
    (
        source.cliente_original_id,
        source.nome_cliente,
        source.email,
        source.telefone,
        source.cpf_cnpj,
        source.data_nascimento,
        source.genero,
        source.tipo_cliente,
        source.segmento,
        source.score_credito,
        source.categoria_valor,
        source.endereco_completo,
        source.bairro,
        source.cidade,
        source.estado,
        source.pais,
        source.cep,
        source.data_primeiro_cadastro,
        source.data_ultima_compra,
        source.data_ultima_atualizacao,
        source.eh_ativo,
        source.aceita_email_marketing,
        source.eh_cliente_vip
    );
