MERGE dim.DIM_PRODUTO AS target
USING
(
    SELECT
        ? AS produto_original_id,
        ? AS codigo_sku,
        ? AS codigo_barras,
        ? AS nome_produto,
        ? AS descricao_curta,
        ? AS descricao_completa,
        ? AS categoria,
        ? AS subcategoria,
        ? AS linha_produto,
        ? AS marca,
        ? AS fabricante,
        ? AS fornecedor_id,
        ? AS nome_fornecedor,
        ? AS pais_origem,
        ? AS peso_kg,
        ? AS altura_cm,
        ? AS largura_cm,
        ? AS profundidade_cm,
        ? AS cor_principal,
        ? AS material,
        ? AS preco_custo,
        ? AS preco_sugerido,
        ? AS margem_sugerida_percent,
        ? AS eh_perecivel,
        ? AS eh_fragil,
        ? AS requer_refrigeracao,
        ? AS idade_minima_venda,
        ? AS estoque_minimo,
        ? AS estoque_maximo,
        ? AS prazo_reposicao_dias,
        ? AS situacao,
        ? AS data_lancamento,
        ? AS data_descontinuacao,
        ? AS data_cadastro,
        ? AS data_ultima_atualizacao,
        ? AS palavras_chave,
        ? AS avaliacao_media,
        ? AS total_avaliacoes
) AS source
    ON target.produto_original_id = source.produto_original_id
WHEN MATCHED THEN
    UPDATE SET
        target.codigo_sku = source.codigo_sku,
        target.codigo_barras = source.codigo_barras,
        target.nome_produto = source.nome_produto,
        target.descricao_curta = source.descricao_curta,
        target.descricao_completa = source.descricao_completa,
        target.categoria = source.categoria,
        target.subcategoria = source.subcategoria,
        target.linha_produto = source.linha_produto,
        target.marca = source.marca,
        target.fabricante = source.fabricante,
        target.fornecedor_id = source.fornecedor_id,
        target.nome_fornecedor = source.nome_fornecedor,
        target.pais_origem = source.pais_origem,
        target.peso_kg = source.peso_kg,
        target.altura_cm = source.altura_cm,
        target.largura_cm = source.largura_cm,
        target.profundidade_cm = source.profundidade_cm,
        target.cor_principal = source.cor_principal,
        target.material = source.material,
        target.preco_custo = source.preco_custo,
        target.preco_sugerido = source.preco_sugerido,
        target.margem_sugerida_percent = source.margem_sugerida_percent,
        target.eh_perecivel = source.eh_perecivel,
        target.eh_fragil = source.eh_fragil,
        target.requer_refrigeracao = source.requer_refrigeracao,
        target.idade_minima_venda = source.idade_minima_venda,
        target.estoque_minimo = source.estoque_minimo,
        target.estoque_maximo = source.estoque_maximo,
        target.prazo_reposicao_dias = source.prazo_reposicao_dias,
        target.situacao = source.situacao,
        target.data_lancamento = source.data_lancamento,
        target.data_descontinuacao = source.data_descontinuacao,
        target.data_cadastro = source.data_cadastro,
        target.data_ultima_atualizacao = source.data_ultima_atualizacao,
        target.palavras_chave = source.palavras_chave,
        target.avaliacao_media = source.avaliacao_media,
        target.total_avaliacoes = source.total_avaliacoes
WHEN NOT MATCHED BY TARGET THEN
    INSERT
    (
        produto_original_id,
        codigo_sku,
        codigo_barras,
        nome_produto,
        descricao_curta,
        descricao_completa,
        categoria,
        subcategoria,
        linha_produto,
        marca,
        fabricante,
        fornecedor_id,
        nome_fornecedor,
        pais_origem,
        peso_kg,
        altura_cm,
        largura_cm,
        profundidade_cm,
        cor_principal,
        material,
        preco_custo,
        preco_sugerido,
        margem_sugerida_percent,
        eh_perecivel,
        eh_fragil,
        requer_refrigeracao,
        idade_minima_venda,
        estoque_minimo,
        estoque_maximo,
        prazo_reposicao_dias,
        situacao,
        data_lancamento,
        data_descontinuacao,
        data_cadastro,
        data_ultima_atualizacao,
        palavras_chave,
        avaliacao_media,
        total_avaliacoes
    )
    VALUES
    (
        source.produto_original_id,
        source.codigo_sku,
        source.codigo_barras,
        source.nome_produto,
        source.descricao_curta,
        source.descricao_completa,
        source.categoria,
        source.subcategoria,
        source.linha_produto,
        source.marca,
        source.fabricante,
        source.fornecedor_id,
        source.nome_fornecedor,
        source.pais_origem,
        source.peso_kg,
        source.altura_cm,
        source.largura_cm,
        source.profundidade_cm,
        source.cor_principal,
        source.material,
        source.preco_custo,
        source.preco_sugerido,
        source.margem_sugerida_percent,
        source.eh_perecivel,
        source.eh_fragil,
        source.requer_refrigeracao,
        source.idade_minima_venda,
        source.estoque_minimo,
        source.estoque_maximo,
        source.prazo_reposicao_dias,
        source.situacao,
        source.data_lancamento,
        source.data_descontinuacao,
        source.data_cadastro,
        source.data_ultima_atualizacao,
        source.palavras_chave,
        source.avaliacao_media,
        source.total_avaliacoes
    );
