MERGE dim.DIM_VENDEDOR AS target
USING
(
    SELECT
        ? AS vendedor_original_id,
        ? AS nome_vendedor,
        ? AS nome_exibicao,
        ? AS cpf,
        ? AS matricula,
        ? AS email,
        ? AS email_pessoal,
        ? AS telefone_celular,
        ? AS telefone_comercial,
        ? AS cargo,
        ? AS nivel_senioridade,
        ? AS departamento,
        ? AS area,
        ? AS equipe_id,
        ? AS nome_equipe,
        ? AS gerente_id,
        ? AS nome_gerente,
        ? AS estado_atuacao,
        ? AS cidade_atuacao,
        ? AS territorio_vendas,
        ? AS tipo_vendedor,
        ? AS meta_mensal_base,
        ? AS meta_trimestral_base,
        ? AS percentual_comissao_padrao,
        ? AS tipo_comissao,
        ? AS total_vendas_mes_atual,
        ? AS total_vendas_mes_anterior,
        ? AS percentual_meta_mes_anterior,
        ? AS ranking_mes_anterior,
        ? AS total_vendas_acumulado_ano,
        ? AS data_contratacao,
        ? AS data_primeira_venda,
        ? AS data_ultima_venda,
        ? AS data_desligamento,
        ? AS data_ultima_atualizacao,
        ? AS situacao,
        ? AS eh_ativo,
        ? AS eh_lider,
        ? AS aceita_novos_clientes,
        ? AS observacoes,
        ? AS motivo_desligamento
) AS source
    ON target.vendedor_original_id = source.vendedor_original_id
WHEN MATCHED THEN
    UPDATE SET
        target.nome_vendedor = source.nome_vendedor,
        target.nome_exibicao = source.nome_exibicao,
        target.cpf = source.cpf,
        target.matricula = source.matricula,
        target.email = source.email,
        target.email_pessoal = source.email_pessoal,
        target.telefone_celular = source.telefone_celular,
        target.telefone_comercial = source.telefone_comercial,
        target.cargo = source.cargo,
        target.nivel_senioridade = source.nivel_senioridade,
        target.departamento = source.departamento,
        target.area = source.area,
        target.equipe_id = source.equipe_id,
        target.nome_equipe = source.nome_equipe,
        target.gerente_id = source.gerente_id,
        target.nome_gerente = source.nome_gerente,
        target.estado_atuacao = source.estado_atuacao,
        target.cidade_atuacao = source.cidade_atuacao,
        target.territorio_vendas = source.territorio_vendas,
        target.tipo_vendedor = source.tipo_vendedor,
        target.meta_mensal_base = source.meta_mensal_base,
        target.meta_trimestral_base = source.meta_trimestral_base,
        target.percentual_comissao_padrao = source.percentual_comissao_padrao,
        target.tipo_comissao = source.tipo_comissao,
        target.total_vendas_mes_atual = source.total_vendas_mes_atual,
        target.total_vendas_mes_anterior = source.total_vendas_mes_anterior,
        target.percentual_meta_mes_anterior = source.percentual_meta_mes_anterior,
        target.ranking_mes_anterior = source.ranking_mes_anterior,
        target.total_vendas_acumulado_ano = source.total_vendas_acumulado_ano,
        target.data_contratacao = source.data_contratacao,
        target.data_primeira_venda = source.data_primeira_venda,
        target.data_ultima_venda = source.data_ultima_venda,
        target.data_desligamento = source.data_desligamento,
        target.data_ultima_atualizacao = source.data_ultima_atualizacao,
        target.situacao = source.situacao,
        target.eh_ativo = source.eh_ativo,
        target.eh_lider = source.eh_lider,
        target.aceita_novos_clientes = source.aceita_novos_clientes,
        target.observacoes = source.observacoes,
        target.motivo_desligamento = source.motivo_desligamento
WHEN NOT MATCHED BY TARGET THEN
    INSERT
    (
        vendedor_original_id,
        nome_vendedor,
        nome_exibicao,
        cpf,
        matricula,
        email,
        email_pessoal,
        telefone_celular,
        telefone_comercial,
        cargo,
        nivel_senioridade,
        departamento,
        area,
        equipe_id,
        nome_equipe,
        gerente_id,
        nome_gerente,
        estado_atuacao,
        cidade_atuacao,
        territorio_vendas,
        tipo_vendedor,
        meta_mensal_base,
        meta_trimestral_base,
        percentual_comissao_padrao,
        tipo_comissao,
        total_vendas_mes_atual,
        total_vendas_mes_anterior,
        percentual_meta_mes_anterior,
        ranking_mes_anterior,
        total_vendas_acumulado_ano,
        data_contratacao,
        data_primeira_venda,
        data_ultima_venda,
        data_desligamento,
        data_ultima_atualizacao,
        situacao,
        eh_ativo,
        eh_lider,
        aceita_novos_clientes,
        observacoes,
        motivo_desligamento
    )
    VALUES
    (
        source.vendedor_original_id,
        source.nome_vendedor,
        source.nome_exibicao,
        source.cpf,
        source.matricula,
        source.email,
        source.email_pessoal,
        source.telefone_celular,
        source.telefone_comercial,
        source.cargo,
        source.nivel_senioridade,
        source.departamento,
        source.area,
        source.equipe_id,
        source.nome_equipe,
        source.gerente_id,
        source.nome_gerente,
        source.estado_atuacao,
        source.cidade_atuacao,
        source.territorio_vendas,
        source.tipo_vendedor,
        source.meta_mensal_base,
        source.meta_trimestral_base,
        source.percentual_comissao_padrao,
        source.tipo_comissao,
        source.total_vendas_mes_atual,
        source.total_vendas_mes_anterior,
        source.percentual_meta_mes_anterior,
        source.ranking_mes_anterior,
        source.total_vendas_acumulado_ano,
        source.data_contratacao,
        source.data_primeira_venda,
        source.data_ultima_venda,
        source.data_desligamento,
        source.data_ultima_atualizacao,
        source.situacao,
        source.eh_ativo,
        source.eh_lider,
        source.aceita_novos_clientes,
        source.observacoes,
        source.motivo_desligamento
    );
