MERGE dim.DIM_REGIAO AS target
USING
(
    SELECT
        ? AS regiao_original_id,
        ? AS pais,
        ? AS regiao_pais,
        ? AS estado,
        ? AS nome_estado,
        ? AS cidade,
        ? AS codigo_ibge,
        ? AS cep_inicial,
        ? AS cep_final,
        ? AS ddd,
        ? AS populacao_estimada,
        ? AS area_km2,
        ? AS densidade_demografica,
        ? AS tipo_municipio,
        ? AS porte_municipio,
        ? AS pib_per_capita,
        ? AS idh,
        ? AS latitude,
        ? AS longitude,
        ? AS fuso_horario,
        ? AS data_cadastro,
        ? AS data_ultima_atualizacao,
        ? AS eh_ativo
) AS source
    ON target.regiao_original_id = source.regiao_original_id
WHEN MATCHED THEN
    UPDATE SET
        target.pais = source.pais,
        target.regiao_pais = source.regiao_pais,
        target.estado = source.estado,
        target.nome_estado = source.nome_estado,
        target.cidade = source.cidade,
        target.codigo_ibge = source.codigo_ibge,
        target.cep_inicial = source.cep_inicial,
        target.cep_final = source.cep_final,
        target.ddd = source.ddd,
        target.populacao_estimada = source.populacao_estimada,
        target.area_km2 = source.area_km2,
        target.densidade_demografica = source.densidade_demografica,
        target.tipo_municipio = source.tipo_municipio,
        target.porte_municipio = source.porte_municipio,
        target.pib_per_capita = source.pib_per_capita,
        target.idh = source.idh,
        target.latitude = source.latitude,
        target.longitude = source.longitude,
        target.fuso_horario = source.fuso_horario,
        target.data_cadastro = source.data_cadastro,
        target.data_ultima_atualizacao = source.data_ultima_atualizacao,
        target.eh_ativo = source.eh_ativo
WHEN NOT MATCHED BY TARGET THEN
    INSERT
    (
        regiao_original_id,
        pais,
        regiao_pais,
        estado,
        nome_estado,
        cidade,
        codigo_ibge,
        cep_inicial,
        cep_final,
        ddd,
        populacao_estimada,
        area_km2,
        densidade_demografica,
        tipo_municipio,
        porte_municipio,
        pib_per_capita,
        idh,
        latitude,
        longitude,
        fuso_horario,
        data_cadastro,
        data_ultima_atualizacao,
        eh_ativo
    )
    VALUES
    (
        source.regiao_original_id,
        source.pais,
        source.regiao_pais,
        source.estado,
        source.nome_estado,
        source.cidade,
        source.codigo_ibge,
        source.cep_inicial,
        source.cep_final,
        source.ddd,
        source.populacao_estimada,
        source.area_km2,
        source.densidade_demografica,
        source.tipo_municipio,
        source.porte_municipio,
        source.pib_per_capita,
        source.idh,
        source.latitude,
        source.longitude,
        source.fuso_horario,
        source.data_cadastro,
        source.data_ultima_atualizacao,
        source.eh_ativo
    );
